=== gartner/DB_DataObject_FormBuilder_Frontend/example/dtd/DB_DataObject_FormBuilder_Frontend-v1.0.dtd
<!ELEMENT frontend      (defaults, tables)>
<!ELEMENT tables        (table*)>

<!ELEMENT defaults      (description, recordsPerPage, allowDelete, allowAdd,
                         labels, confirmDelete, deleteMessage, css?, javascriptPath?,
                         cssPath?, fbOptions?, plugins?, dataGridRenderer?, quickForm?)>
<!ATTLIST defaults
displayName             CDATA   #REQUIRED>

<!ELEMENT fbOptions     (fbOption*, requiredNote?)>
<!ELEMENT fbOption      (#PCDATA|key|option)*>
<!--
In reality, all scalar formBuilder-optoins can be set here, and the will be used.
But unless specified as a value for the name-attribute, it will violate the DTD!

Attr:
    requiredRuleMessage: The message displayed when a required field is not filled. Use %s to insert the fields name

    -->
<!ATTLIST fbOption
name                    (addFormHeader|clientRules|createSubmit|crossLinkSeparator|
                        dbDateFormat|dateElementFormat|dateFieldLanguage|dateTimeelementFormat|
                        elementNamePrefix|elementNamePostfix|formHeaderText|hidePrimaryKey|
                        linkDisplayLevel|linkNewValue|linkNewValueText|requiredRuleMessage|
                        ruleViolationMessage|selectAddEmptyLabel|submitText|timeElementFormat|
                        useAccessors|useMutators|useCallTimePassByReference|validateOnProcess|
                        booleanFields|crossLinks|crossLinkExtraFields|dateFields|
                        elementTypeAttributes|elementTypeMap|enumFields|enumOptions|
                        fieldAttributes|fieldLabels|fieldsToRender|fieldsRequired|
                        linkDisplayFields|linkElementTypes|linkOrderFields|preDefElements|
                        preDefGroups|preDefOrder|reverseLinks|selectAddEmpty|textFields|
                        timeFields|tripleLinks|userEditableFields)    #REQUIRED>
<!-- The text at the bottom of the form, that explains the fields that are required -->
<!ELEMENT requiredNote  (#PCDATA)>

<!-- Customize the datagrid-renderer -->
<!ELEMENT dataGridRenderer      (dataGridRendererAttribute*,dataGridRendererOption*)>
<!-- This is html-attributes for the renderer (This is always a table-tag) -->
<!ELEMENT dataGridRendererAttribute    (#PCDATA)>
<!ATTLIST dataGridRendererAttribute
name                    CDATA   #REQUIRED>
<!--
Options passed to the renderer. The default renderer is Structures_DataGrid_Renderer_HTMLTable
The name-attribute is used as the key in the array passed as rendererOptions
-->
<!ELEMENT dataGridRendererOption    (#PCDATA|option|key)*>
<!ATTLIST dataGridRendererOption
name                    CDATA   #REQUIRED>

<!ELEMENT quickForm     (renderer?, formErrorTemplate?)>
<!ELEMENT renderer      (templates)>
<!ELEMENT templates     (template+)>
<!ELEMENT template      (#PCDATA)>
<!ATTLIST template
name                    (element|form|groupElement|group|header|requiredNote) #REQUIRED>

<!--
Strictly speaking, formErrorTemplate has nothing to do with quickForm
but to keep things a little bit organized, its placed here ...
-->
<!ELEMENT formErrorTemplate     (#PCDATA)>

<!-- key element is deprecated - use option instead -->
<!ELEMENT key           (#PCDATA|key)*>
<!ATTLIST key
name                    CDATA   #IMPLIED>

<!ELEMENT option        (#PCDATA|option)*>
<!ATTLIST option
name                    CDATA   #IMPLIED>

<!ELEMENT table			(name, listName?, displayName, description, recordsPerPage?, allowDelete?,
                        allowAdd?, labels?, confirmDelete?, deleteMessage?,
                        listColumns, css?, fbOptions?, plugins?, dataGridRenderer?, quickForm?)>

<!ATTLIST table
enabled                 (no|yes|0|1)   "yes">

<!ELEMENT plugins       (plugin*)>
<!ATTLIST plugins
policy                  (0|1|disabled|enabled|off|on)   #IMPLIED>

<!ELEMENT plugin        (#PCDATA|pluginLoader|key|option)*>
<!ATTLIST plugin
policy                  (0|1|disabled|enabled|off|on)   #IMPLIED
name                    CDATA       #REQUIRED>

<!ELEMENT pluginLoader              EMPTY>
<!ATTLIST pluginLoader
path                    CDATA       #REQUIRED
className               CDATA       #REQUIRED>


<!ELEMENT css                       EMPTY>
<!ATTLIST css
filename                CDATA       #IMPLIED>

<!ELEMENT javascriptPath            EMPTY>
<!ATTLIST javascriptPath
path                    CDATA       #REQUIRED>

<!ELEMENT cssPath                   EMPTY>
<!ATTLIST cssPath
path                    CDATA       #REQUIRED>

<!ELEMENT name              (#PCDATA)>
<!ELEMENT listName          (#PCDATA)>
<!ELEMENT displayName       (#PCDATA)>
<!ELEMENT description		(#PCDATA)>
<!ELEMENT recordsPerPage	(#PCDATA)>
<!ELEMENT allowDelete		EMPTY>
<!ATTLIST allowDelete
value					(0|1|disabled|enabled|no|yes|off|on)        #REQUIRED>
<!ELEMENT allowAdd			EMPTY>
<!ATTLIST allowAdd
value					(0|1|disabled|enabled|no|yes|off|on)        #REQUIRED>
<!ELEMENT labels        (label+)>

<!ELEMENT label	        (#PCDATA)>
<!ATTLIST label
name					(addNew|delete|edit|deleteConfirmYes|deleteConfirmNo
                        |tableColumn|tableDescription|cancelSubmit|recordsPrPage
                        |recordsPrPageSubmit) #REQUIRED>

<!ELEMENT confirmDelete	EMPTY>
<!ATTLIST confirmDelete
value					(0|1|disabled|enabled|no|yes|off|on)        #REQUIRED>

<!ELEMENT deleteMessage	(#PCDATA)>
<!ELEMENT listColumns   (column+)>

<!ELEMENT column        (#PCDATA|key)*>
<!ATTLIST column
displayName		    CDATA   		        #IMPLIED
allowOrderBy		(0|1|disabled|enabled|no|yes|off|on)            #IMPLIED
type				(raw|callback|dbdocallback|hideshow|boolean|date|inflector)   #IMPLIED
orderby             (asc|desc)             #IMPLIED>

=== gartner/DB_DataObject_FormBuilder_Frontend/src/DB/DataObject/FormBuilder/Frontend/DB_DO_Frontend.dist.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!DOCTYPE frontend
    SYSTEM "http://pear.quercus.palustris.dk/dtd/DB_DataObject_FormBuilder_Frontend-v1.0.dtd">
<frontend>
    <defaults displayName="Alle tabeller">
        <description>Vælg den tabel du vil arbejde med</description>
        <recordsPerPage>25</recordsPerPage>
        <allowDelete value="1" />
        <allowAdd value="1" />
        <labels>
            <label name="addNew">Tilføj ny post</label>
            <label name="delete">Slet</label>
            <label name="edit">Rediger</label>
            <label name="deleteConfirmYes">Ja</label>
            <label name="deleteConfirmNo">Nej</label>
            <label name="tableColumn">Tabel</label>
            <label name="tableDescription">Beskrivelse</label>
            <label name="cancelSubmit">Afbryd</label>
            <label name="recordsPrPage">Vis pr. side</label>
            <label name="recordsPrPageSubmit">Brug!</label>
        </labels>
        <confirmDelete value="1" />
        <deleteMessage>Er du sikker på du vil slette dette?</deleteMessage>
        <css filename="/main.css" />
        <javascriptPath path="/jscripts/" />
        <cssPath path="/css/" />
        <fbOptions>
            <fbOption name="requiredRuleMessage">%s - Skal udfyldes</fbOption>
            <requiredNote>Felter med * skal udfyldes</requiredNote>
        </fbOptions>

        <plugins policy="disabled">
            <plugin name="tinyMCE" policy="disabled">
                <!-- These are the options you would normally pass to tinymce.init() -->
                <key name="options">
                    <key name="content_css">/css/main.css</key>
                </key>
                <!-- Should the options here be merged with the default options of the plugin?
                     If false, only the options set for the plugin will be used. -->
                <key name="mergeOptions">1</key>
            </plugin>

            <plugin name="HtmlDefaultAttributes" policy="enabled">
                <key name="inputLength">80</key>
                <key name="textareaRows">20</key>
                <key name="textareaCols">60</key>
            </plugin>

        </plugins>

        <!-- This is where options for the datagrid renderer is set -->
        <dataGridRenderer>
            <!-- These are attributes to put inside the table-tag of the datagrid. -->
            <dataGridRendererAttribute name="class">datagrid</dataGridRendererAttribute>
            <dataGridRendererAttribute name="style">border: 5px solid black;</dataGridRendererAttribute>

            <!-- This is options passed to the datagrid-dataGridRenderer.
                 The dataGridRenderer used is Structures_DataGrid_dataGridRenderer_HTMLTable
                 See the PEAR-manual on the dataGridRenderer for which options it can use
            -->
            <dataGridRendererOption name="sortIconASC">--hest--</dataGridRendererOption>
            <!-- If a dataGridRenderer-option is an array, use like this -->
            <dataGridRendererOption name="evenRowAttributes">
                <key name="class">oddRow</key>
            </dataGridRendererOption>

        </dataGridRenderer>

    </defaults>

    <tables>
        <table>
            <name>tbl_kategorier</name>
            <displayName>Kategorier</displayName>
            <description>Kategorier som billeder kan placeres i.</description>
            <recordsPerPage>25</recordsPerPage>
            <allowDelete value="1" />
            <allowAdd value="1" />
            <labels>
                <label name="addNew">Tilføj ny kategori</label>
                <label name="delete">Slet</label>
                <label name="edit">Rediger</label>
                <label name="deleteConfirmYes">Ja</label>
                <label name="deleteConfirmNo">Nej</label>
            </labels>
            <confirmDelete value="1" />
            <deleteMessage>Er du sikker på du vil slette dette?</deleteMessage>
            <listColumns>
                <column displayName="Kategorinavn">navn</column>
            </listColumns>
        </table>

        <table>
            <name>tbl_billedinfo</name>
            <displayName>Billeder</displayName>
            <description>Her er billederne.</description>
            <recordsPerPage>25</recordsPerPage>
            <allowDelete value="1" />
            <allowAdd value="1" />
            <listColumns>
                <column displayName="pk" orderby="desc">id</column>
                <column>titel</column>
                <column displayName="Billede" type="raw" allowOrderBy="0">image_tag</column>
            </listColumns>
            <fbOptions>
                <fbOption name="requiredRuleMessage">%s - Skal udfyldes</fbOption>
            </fbOptions>
        </table>

    </tables>

</frontend>

=== gartner/DB_DataObject_FormBuilder_Frontend/example/examples/simple/3/frontend-simple.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!DOCTYPE frontend
        SYSTEM "http://pear.quercus.palustris.dk/dtd/DB_DataObject_FormBuilder_Frontend-v1.0.dtd">
<frontend>
    <defaults displayName="All tables">
        <description>Choose table to list</description>
        <recordsPerPage>25</recordsPerPage>
        <allowDelete value="1" />
        <allowAdd value="1" />
        <labels>
            <label name="addNew">Add new record</label>
            <label name="delete">Delete</label>
            <label name="edit">Edit</label>
            <label name="deleteConfirmYes">Yes</label>
            <label name="deleteConfirmNo">No</label>
            <label name="tableColumn">Table</label>
            <label name="tableDescription">Description</label>
            <label name="cancelSubmit">Abort</label>
            <label name="recordsPrPage">Show pr. page</label>
            <label name="recordsPrPageSubmit">Use!</label>
        </labels>
        <confirmDelete value="1" />
        <deleteMessage>Sure you want to delete this?</deleteMessage>
        <css filename="/css/datagrid.css"/>
        <fbOptions>
            <fbOption name="requiredRuleMessage">%s - Required field</fbOption>
            <requiredNote>Fields marked with * are required</requiredNote>
        </fbOptions>

        <plugins policy="disabled">

        </plugins>

    </defaults>

    <tables>
        <table>
            <name>categories</name>
            <displayName>Categories</displayName>
            <description>Categories that images can belong to</description>
            <labels>
                <label name="addNew">Add category</label>
            </labels>
            <listColumns>
                <column displayName="Name">name</column>
            </listColumns>
        </table>

        <table>
            <name>pictures</name>
            <displayName>Pictures</displayName>
            <description>Pictures in the system.</description>
            <listColumns>
                <column displayName="pk" orderby="desc">id</column>
                <column>title</column>
                <column displayName="x">width</column>
                <column displayName="y">height</column>
            </listColumns>
        </table>

    </tables>

</frontend>
